.gitmodules
Switch the submodules to use https:// instead.
=> git:// protocol isn't recommended for accessing GitHub repositories.

src/scan_windirs.cpp
Fixes issue where NTFS filesize was always being set to 1000000000000 ("terabyte")
=> Fix windirs NTFS MFT FNAME filesize bug

src/scan_hiberfile.cpp, src/scan_ntfsusn.cpp
Hi, I changed 3 parts.
1. scan_hiberfile.cpp
When I tested record carving function in hiberfil.sys, it seemed some uncompressed size of XPRESS data was not enough slightly. I compared current code in BE with latest code in Hibr2Bin (https://github.com/comaeio/Hibr2Bin). I have changed code with determination of compressed size. I don't understand XPRESS decompressed algorithm details, but this change works for my test data.
2. scan_ntfsusn.cpp
Convert CR+LF to LF.
3. scan_ntfsusn.cpp
To improve carving process, it distinguished between valid record and corrupt record.
=> improved ntfsusn and hiberfile scanner

src/scan_accts.flex
This pull request adds a recorder and regular expressions for Canadian Social Insurance Numbers (SINs) to the scan_accts.flex scanner. Results are written to a new feature file `sin.txt`.
I hope you'll consider merging this into the master repo and I welcome any suggestions for improvement. Thanks!
=> Add Canadian SIN recorder and regexps

src/scan_accts.flex, src/scan_accts_lg.cpp
This fixes an error in one of the regular expressions to identify Canadian Social Insurance Numbers (SINs) in the `accts` scanner and adds a feature recorder and regular expressions for SINs to `accts_lg`.
Should be the last PR for a while (eventually I'd also like to add some additional functionality to these scanners, e.g. to identify SWIFT and IBAN numbers, but the SIN scanning functionality is the priority for now).
Thanks!
=> Canadian SIN scanner improvements

configure.ac
Update configure.ac, Java may or may not include "1." at the start of the version string.
=> Java Version Checking

etc/CONFIGURE_UBUNTU18LTS.bash
Updating URL for Cloning GIT
The URL in the original file is not working:
bulkextractor: command not found
gra@NPCB214Gra:~$ git clone --recursive git@github.com:simsong/bulk_extractor.git
Cloning into 'bulk_extractor'...
The authenticity of host 'github.com (140.82.118.3)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,140.82.118.3' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
-> New URL was taken from actual Github Project
=> Updating URL for Git Project in Ubuntu 18.04 LTS

etc/CONFIGURE_UBUNTU16LTS.bash
Updating URL for Cloning GIT
The URL in the original file is not working:
bulkextractor: command not found
gra@NPCB214Gra:~$ git clone --recursive git@github.com:simsong/bulk_extractor.git
Cloning into 'bulk_extractor'...
The authenticity of host 'github.com (140.82.118.3)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,140.82.118.3' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
-> New URL was taken from actual Github Project
=> Updating URL for Git Project in Ubuntu 16.04 LTS

COPYING
Currently running `sh bootstrap.sh' will overwrite COPYING since the link points to a non-existing file.
=> Updated COPYING symbolic link

plugins/plugin_test.cpp
The size_t hack should check for `__clang__`, not for `__APPLE__`.
Same fix to be sent for `be13_api` and `dfxml` subrepositories, which contain similar code.
=> Fix build on OpenBSD

Makefile.am, configure.ac, etc/CONFIGURE_AMAZON_LINUX.bash, etc/CONFIGURE_CENTOS7.bash, etc/CONFIGURE_DEBIAN9.bash, etc/CONFIGURE_FEDORA31.bash, etc/CONFIGURE_FEDORA32.bash, etc/CONFIGURE_UBUNTU16LTS.bash, etc/CONFIGURE_UBUNTU18LTS.bash, src/scan_json.cpp, tests/Data/json_log.txt, tests/Data/json_plain.txt
Dear Simson,
this PR modifies `src/scan_json.cpp` to use the library `json-c` instead of source code under a non-free license.
Furthermore I added two files for testing the correct extraction of JSON-strings and hooked `-ljson-c` into the automake-system.
In addition I added the package `libjson-c-dev{,el} ` to the installation routines in the installation scripts stored under `etc/`.
I kindly ask you to review the newly added code.
If there are any issues with the changes, please let me know. 
If not, I will start to work on the creation of a .deb-package of bulk_extractor for the Debian package archives soon. 
Best regards
Jan
=> Modify scan_json.cpp to use the libary json-c

LICENSE.md, src/scan_json.cpp
Dear Simson, 
this PR fixes a compilation issue introduced by #170, which stemmed from using a function named `json_tokener_get_parse_end(...)`. This function was introduced in version 0.15 of libjson-c, whereas this library version is not available in Ubuntu's package sources yes. Calling this not existing function resulted in 
https://github.com/simsong/bulk_extractor/runs/2910172008?check_suite_focus=true#step:5:579, which should be fixed now.
Best regards   
Jan
=> Fix src/scan_json.cpp to compile with libjson-c versions < 0.15

src/exif_entry.cpp, src/main.cpp
Dear Simson, 
this PR fixes two spelling errors. This patch was created by @sbrun in the course of packaging bulk_extractor for Kali.
I think, it is a good idea forward it to you, so that it finds its way inside the upstream code base. 
Best regards,
Jan
=> Fix spelling errors (patch from S. Brun)

etc/CONFIGURE_UBUNTU18LTS.bash
The apt autoremove on line 58 had a duplicate autoremove, this is interpreted as a package by apt and throws an error.
=> Duplicate autoremove in Ubuntu 18 config script

etc/CONFIGURE_UBUNTU20LTS.bash
ftpmirror URL doesn't work so replaced with working URLs for AUTOCONF and AUTOMAKE
=> ftpmirror url for autoconf & automake updated

README.md
I think it would be useful to mention in the README.md that you need to run `bootstrap.sh` to generate the configure command. I don't believe it's mentioned in the INSTALL, but people will probably see the README on GitHub first anyway.
=> Include bootstrap.sh instructions

src/image_process.cpp, src/image_process.h
As mentioned in #258 `std::filesystem::file_size` does not work on block files.
- Replaced code to calculate the size of Unix block devices
=> Replace previous code for size of unix block files

.github/workflows/create-tarball.yml
Dear Simson,
this PR provides a GitHub workflow that creates a tarball including all submodules. The workflow is configured to be triggered manually from the default branch, as described [here](https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow).
Maybe this is of interest since it could ease distributing new versions of `bulk_extractor`. 
Best regards, 
jgru
=> Add a workflow to release a tarball including all submodules

.github/workflows/create-tarball.yml
Dear Simson,
this PR addresses #371 by restricting permissions of `secrets.GITHUB_TOKEN` in the workflow file to publish a release. All permissions are removed except the one to write contents, which is needed to place the tarball in the release section according to the [documentation](https://docs.github.com/en/rest/overview/permissions-required-for-github-apps#permission-on-contents).
Best regards,
jgru
=> Restrict permissions of secrets.GITHUB_TOKEN in workflow

src/scan_rar.cpp
Building v2.0.0 and Git HEAD both fail when configuring `--disable-rar` with:
```
scan_rar.cpp:611:23: error: member reference base type 'uint64_t' (aka 'unsigned long long') is not a structure or union
sp.info->flags.default_enabled = false;
~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [scan_rar.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```
Updating `flags` to `scanner_flags` should at least get build to finish. Not sure if there are any other issues.
=> fix --disable-rar build

Makefile.am
Two small typo corrections on the same comment line. The first correction was a misspelling ("shoudln't" into "shouldn't") and the second change was capitalizing the beginning of a sentence ("don't" into "Don't").
=> Minor typo fix in program comment

src/bulk_extractor.cpp, src/test_be3.cpp
Fixes #430 
Disable scanners provided in arguments before enabling other scanners. This solves a bug where using `-x all` results in no scanners being active regardless of `-e` arguments provided.
=> Disable scanners before enabling

bootstrap.sh
See https://github.com/simsong/bulk_extractor/issues/452
=> add extra help

.github/workflows/coverity.yml
Based on https://scan.coverity.com/projects/simsong-bulk_extractor , it appears that you registered the Coverity project as `simsong/bulk_extractor` . This change changes the COVERITY_PROJECT_NAME to refer to `simsong/bulk_extractor` .
=> coverity.yml: Change Coverity project name to simsong/bulk_extractor
